
collections:
## - name: cisco.asa
## - name: servicenow.itsm
## - name: servicenow.servicenow
## - name: ansible.tower
- name: ansible.controller
  version: 4.6.8
## - name: chocolatey.chocolatey
## - name: azure.azcollection
## - name: community.docker
## - name: community.general
## - name: amazon.aws
## - name: community.aws
## - name: cisco.ios
## - name: ansible.posix
## - name: infoblox.nios_modules
## - name: http://172.16.1.25:8080/dynatrace-oneagent-ansible-1.1.0.20211006-104525.tar.gz
