---
- hosts: all
  name: Windows application management playbook
  vars:
    state: present
    packages:
      - googlechrome
      - avgantivirusfree

  tasks:
  - name: Install Windows Packages
    win_chocolatey:
      name: "{{ packages }}"
      state: "{{ state }}"
      ignore_checksums: true
    become_user: Administrator
    become_method: runas
