---
- name: RHEL  
  hosts: all
  gather_facts: false

  tasks:
    #- name: enable cisco_ios interface gigabit

    #- name: print all cisco_ios facts
       
    #- name: print all cisco_ios facts with gather_subset as a {{var}}

    # Validate ansible can connect to inventory & create a new dyanmic inventory & continue to run setup
    
    


    # Install postgresql-server & run postgresql-setup command & enable postgresql-server to start at boot
    # Content suggestion provided by Ansible Lightspeed
    - name: Install postgresql-server
      when: ansible_os_family == "RedHat"
      ansible.builtin.package:
        name: postgresql-server
        state: present

    - name: Run postgresql-setup command
      ansible.builtin.command: postgresql-setup initdb
      when: ansible_os_family == "RedHat"

    - name: Enable postgresql-server to start at boot
      ansible.builtin.service:
        name: postgresql
        enabled: true
    
   

    # Setup and ec2 host xl.large with datadog package installed
 
     
    - name: Install postgresql-server & postgresql-setup command

    

    - name: Enable postgresql-server to start at boot
  
    #- name: show running config

    #- name: update all packages on rhel when version is 8

    #- name: debug msg of ansible_facts

    #- name: add Appstream repo
    
    #- name: add Appstream repo to rhel 8

    #- name: create vlan on cisco_ios

    #- name: change snmp community strings on cisco_ios

    #- name: configure layer3 interface for ios

    #- name: create a login banner on ios

    #- name: backup cisco ios configuration

    #- name: add an ip access list on ios

    #- name: configure bgp on ios

    #- name: configure bgp on ios using ios_bgp
     
    #- name: Merge provided OSPF Interfaces configuration

    #- name: create a list of users on rhel machine based on groups






