---
- name: Installing requested package
  hosts: all
  gather_facts: False
  vars:
      package: ''
  serial: 1
  tasks:
    - name: Install {{package}}
      ansible.builtin.apt:
        name: plexmediaserver
        state: latest
