---
- name: Create Linux VM in inventory
  hosts: localhost  
  connection: local
  gather_facts: no
  vars:
    tower_user: 
    tower_password:
    vm_name: rhel7-0088
    tower_inventory: 'Linux Inventory'
   
  tasks:
   - name: Create host in inventory to pass to next playbook using tower-cli host create -n
     shell: |
       tower-cli config host localhost
       tower-cli config verify_ssl false
       tower-cli login {{ tower_user }} --password {{ tower_password }}
       tower-cli host create -n {{ vm_name }} -i {{ tower_inventory }} --variables='{"ansible_user":"root", "ansible_host":"100.9.133.13"}'
     no_log: false

   #- name: Create host in inventory to pass to next playbook using tower-cli host create -n
   #  command: "{{ item }}"
   #  no_log: true
   #  with_items:
   #    - tower-cli config host localhost
   #    - tower-cli login {{ tower_user }} --password {{ tower_password }}
   #    - tower-cli host create -n {{ vm_name }} -i 'Linux Inventory' --variables='{"ansible_user":"root", "ansible_host":"100.9.133.13"}'
