---
- name: Installing requested package
  hosts: all
  gather_facts: False
  vars:
      package: ''

  tasks:
    - name: Remove HTTPD / HTTPD-TOOLS
      yum:
        name:
          - httpd
          - httpd-tools
        state: absent
    - name: Install old version httpd-2.4.6-31.el7_1.1
      yum:
        name:
          - httpd-2.4.6-31.el7_1.1

        state: present
