- name: software patch demo (httpd using yum package manager) with rollback
  hosts: all
  vars:
    package: httpd
    sn_host_name:

  tasks:
   - name: Get package version
     yum:
       list: "{{ package }}"
     register: software_version
     become: true

   - name: Read which version is installed and available
     set_fact:
       software_update: false
       software_version_installed: "{{ software_version | json_query(\"results[?yumstate=='installed'].release\") | last }}"
       software_version_available: "{{ software_version | json_query(\"results[?yumstate=='available'].release\") }}"
   - debug:
       var: software_version_installed
   - debug:
       var: software_version_available


   - name: SERVICENOW incident created if Available Software Update for "{{ package }}" from Vendor detected
     servicenow.itsm.incident:
       state: new
       short_description: "Software Update Available on {{sn_host_name}}, {{inventory_hostname}} was found for Software Package {{ package }}. The installed version is too old."
       #priority: 5
       urgency: 3
       #approval: requested
       caller: "Ansible Automation Platform"
       description: "An automated software version update check on {{sn_host_name}}, {{inventory_hostname}} found an update available from the vendor. However the current version is too old and dependencies need to be installed for the latest cerfified release. \n--------\n The current version of software is {{software_version_installed}}.\n--------\n The available version(s) of software is/are {{software_version_available}}. \n--------\n Recommendation: The newer dependencies should be installed before updating to the new certified version of the package. This version needs to be approved by the application/package owner before proceeding with patching process. Do you wish to proceed? Please approve this ticket if so. This ticket was generated by Ansible Tower API call.\n--------\n "
     register: snow_var
     delegate_to: localhost
     when: software_version_installed=="31.el7_1.1"

   - name: DEBUG SNOW_VAR
     debug:
       var: snow_var.record.number
