---
- name: Overwrite acls on ASA
  hosts: all
  connection: network_cli
  gather_facts: no

  tasks:
   - name: Task {{ state }} acl on {{ inventory_hostname }}
     cisco.asa.asa_acls:
       config:
         acls:
           - name: "{{ acl_name }}"
             acl_type: extended
             aces:
             - grant: deny
               line: 1
               protocol_options:
                 tcp: true
               source:
                 address: "{{ source_net }}"
                 netmask: 255.255.255.0
                 port_protocol:
                   eq: "{{ source_port }}"
               destination:
                 address: "{{ dest_net }}"
                 netmask: 255.255.255.0
                 port_protocol:
                   eq: "{{ dest_port }}"
       state: "{{ state }}"
     register: ACL_Changes
   - name: debug ACL_Changes
     debug:
       var: ACL_Changes.commands

   - name: Send Alert to Slack
     slack:
      token: "{{ slack_token }}"
      msg: "Ansible made the following changes*({{ inventory_hostname }})* \n
   *Action*: {{ state }} \n
   *Changes Made*: \n ```{{ ACL_Changes.commands | to_nice_json }}``` "
      channel: "{{ channel }}"
      username: "{{ slackuser }}"
     run_once: true
     delegate_to: localhost
