---
- name: Start Backup of Network Devices
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: ''
    ansible_network_os: ''


  tasks:
  - name: Backup the config
    ios_config:
      backup: yes
      backup_options:
        dir_path: "{{backup_path}}"
        filename: "{{inventory_hostname}}.cfg"
    register: config_output

  - name:
    copy:
       src: "{{backup_path}}/{{inventory_hostname}}.cfg"
       dest: "/home/{{inventory_hostname}}.cfg"
