---
- hosts: all
tasks:
- name: show int status
ios_command:
  commands:
    - show interface Eth1/57 status
register: output

- debug:
  msg: "{{ item }}"
when: '"connected" in item'
loop: "{{ output.stdout_lines.0 }}"
