---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  gather_facts: false

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: webservers:Type_webservers:tag_Type_webservers:tag_Name_webserver_tf
  remote_user: ec2-user

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: dbservers:Type_dbservers:tag_Type_dbservers:tag_Name_dbserver_tf


  roles:
    - db
