---
- name: Ready Clean Machine for demo
  hosts: all
  gather_facts: false
  vars:
     username: ''
     password: ''
     pool_id: ''
     systemrole: "Red Hat Enterprise Server"
     usage: "Dev/Test"
     sla: "Self-Support"

  tasks:
    - name: Unregistering Insights
      command: insights-client --unregister
      ignore_errors: yes
    - name: Unsubscribing to RHEL account now
      redhat_subscription:
        state: absent
