---
- name: Export Controller data
  hosts: localhost
  gather_facts: False

  tasks:
    - name: add Python module
      ansible.builtin.pip:
        name: awxkit
        extra_args: --upgrade
      delegate_to: localhost
      run_once: true

    - name: Call current controller and export specific asset
      ansible.controller.export:
        organizations: 'all'
        controller_host: 172.16.1.24
        controller_username: 'admin'
        controller_password: 'r3dh2t!'
        validate_certs: false
      register: export_output

    - name: Show Export
      debug:
        msg: "{{ export_output }}"
        verbosity: 2

    - name: Import Exported data
      ansible.controller.import:
        assets: "{{ export_output.assets}}"
        controller_host: 172.16.1.23
        controller_username: 'admin'
        controller_password: 'r3dh2t!'
        validate_certs: false
