
---
- name: build Ios inventory report
  hosts: ios
  gather_facts: False

  vars:
    www_dir: ''
    network_html_dir: "{{ www_dir }}"
    network_inv_file: "{{ network_html_dir }}/report.html"
    desired_version: ''

  tasks:
  - name: 'Preflight Varible check :: ansible_network_os'
    fail: msg='Please include the ansible_network_os to the variable "ansible_network_os"'
    run_once: true
    when: 'ansible_network_os is not defined'
  - name: 'Preflight Varible check :: ansible_connection'
    fail: msg='Please include the ansible_connection to the variable "ansible_connection"'
    run_once: true
    when: 'ansible_connection is not defined'
  - name: 'Preflight Varible check :: www_dir'
    fail: msg='Please include the www_dir to the variable "www_dir"'
    run_once: true
    when: 'www_dir is not defined'
  - name: 'Preflight Varible check :: desired_version'
    fail: msg='Please include the desired_version to the variable "desired_version"'
    run_once: true
    when: 'desired_version is not defined'
  - name: 'Preflight Varible check :: slack_token'
    fail: msg='Please include the slack_token to the variable "slack_token"'
    run_once: true
    when: 'slack_token is not defined'





  - name: gathering all IOS facts
    ios_facts:
    register: all_facts

  - name: create HTML report
    template:
      src: report-ios.j2
      dest: "{{ network_inv_file }}"
    delegate_to: localhost
    run_once: true
  - name: Send Alert to Slack
    slack:
      token: "{{ slack_token }}"
      msg: 'Please check report http://172.16.1.25/:8080/report.html'
      channel: '#toweralerts'
      username: 'Ansible Tower'
    run_once: true
    delegate_to: localhost
