---
- name: Download OneAgent installer in specific version to a custom location
  gather_facts: False
  hosts: all


  tasks:
    - name: Grab oneagent from instance
      ansible.builtin.get_url:
        url: 'https://juz21888.live.dynatrace.com/api/v1/deployment/installer/agent/unix/default/latest?arch=x86&flavor=default'
        dest: "{{ oneagent_installpath }}{{ oneagent_version }}"
        headers:
          Authorization: Api-Token {{ oneagent_paas_token }}
    - name: Make file executable
      ansible.builtin.file:
        path: "{{ oneagent_installpath }}{{ oneagent_version}}"
        owner: root
        group: root
        mode: '755'
    - name: Install Dynatrace OneAgent
      ansible.builtin.command:
        cmd: "{{ oneagent_installpath }}{{ oneagent_version }} --set-infra-only=false --set-app-log-content-access=true"
    - name: Restart Services to have monitored
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - httpd 
        - nginx 
        - podman 
        - receptor 
        - postgresql
        - mariadb  
      ignore_errors: true
    
